# Generated by Django 6.0.3 on 2026-05-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=20)),
                ('genere', models.CharField(choices=[('sceince', 'sceince'), ('friction', 'friction'), ('technology', 'technology'), ('fairy tale', 'fairy tale')], max_length=10)),
            ],
        ),
    ]
