# Generated by Django 6.0.6 on 2026-07-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
