# Generated by Django 6.0.6 on 2026-07-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='genere',
            name='code',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.PositiveIntegerField(),
        ),
    ]
