# Generated by Django 6.0.6 on 2026-07-06 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_genere_code_alter_book_book_id_alter_book_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
