# Generated by Django 6.0.6 on 2026-07-06 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(verbose_name=datetime.datetime(2026, 7, 6, 7, 0, 32, 750467, tzinfo=datetime.timezone.utc)),
        ),
    ]
