# Generated by Django 6.0.6 on 2026-07-06 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avilable_quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(verbose_name=datetime.datetime(2026, 7, 6, 11, 11, 25, 351657, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
