# Generated by Django 6.0.6 on 2026-07-06 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_avilable_quantity_alter_book_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 7, 6, 12, 47, 14, 917821, tzinfo=datetime.timezone.utc)),
        ),
    ]
