# Generated by Django 6.0.3 on 2026-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('register_no', models.CharField(max_length=10)),
                ('admission_year', models.IntegerField()),
                ('department', models.CharField(choices=[('CSE', 'CSE'), ('EC', 'EC'), ('CE', 'CE'), ('ME', 'ME'), ('EEE', 'EEE')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
            ],
        ),
    ]
