# Generated by Django 6.0.6 on 2026-07-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(default='12', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.department'),
            preserve_default=False,
        ),
    ]
