# Generated by Django 6.0.6 on 2026-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
