# Generated by Django 6.0.6 on 2026-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_reg_no_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='cd', max_length=10),
            preserve_default=False,
        ),
    ]
