# Generated by Django 6.0.6 on 2026-07-03 07:20

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(student.models.Student.max_admission_year)]),
            preserve_default=False,
        ),
    ]
