# Generated by Django 6.0.6 on 2026-07-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_alter_book_category'),
        ('student', '0002_department_student_reg_no_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_date', models.DateTimeField()),
                ('submission_date', models.DateTimeField()),
                ('submitted_date', models.DateTimeField()),
                ('transaction_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='book.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='student.student')),
            ],
        ),
    ]
