# Generated by Django 6.0.6 on 2026-07-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
