# Generated by Django 6.0.6 on 2026-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_submitted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
